In [57]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.cluster import KMeans
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from scipy.spatial.distance import cdist

In [58]:
caminho_parquet = r"C:\Users\Pichau\INMET\TODAS_ESTACOES\df_intermediario.parquet"

df_intermediario = pd.read_parquet(caminho_parquet)

# TEMPERATURA - Kmeans

In [60]:
print(df_intermediario[['VARIACAO PRIMEIRA HORA ANTERIOR TEMPERATURA AMBIENTE']].isnull().sum())

print(df_intermediario[['VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA AMBIENTE']].isnull().sum())

print(df_intermediario[['VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA AMBIENTE']].isnull().sum())

VARIACAO PRIMEIRA HORA ANTERIOR TEMPERATURA AMBIENTE    135
dtype: int64
VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA AMBIENTE    135
dtype: int64
VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA AMBIENTE    135
dtype: int64

In [61]:
df_intermediario = df_intermediario.dropna(subset=['VARIACAO PRIMEIRA HORA ANTERIOR TEMPERATURA AMBIENTE'])
df_intermediario = df_intermediario.dropna(subset=['VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA AMBIENTE'])
df_intermediario = df_intermediario.dropna(subset=['VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA AMBIENTE'])

In [62]:
# Remover as linhas onde a coluna tem valores maiores que 50, só tenho 1 caso, no caso é devido a dados faltantes.  
df_intermediario = df_intermediario[df_intermediario['VARIACAO PRIMEIRA HORA ANTERIOR TEMPERATURA AMBIENTE'] < 20]
df_intermediario = df_intermediario[df_intermediario['VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA AMBIENTE'] < 20]
df_intermediario = df_intermediario[df_intermediario['VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA AMBIENTE'] < 20]


# A menor temperatura já registrada no RJ foi de  8,3ºC , temos temperaturas abaixo nos nossos dados, até negativas, serão removidas. 

df_intermediario = df_intermediario[df_intermediario['Temp_Amb_min'] >= 8]

In [63]:
df_intermediario[['VARIACAO PRIMEIRA HORA ANTERIOR TEMPERATURA AMBIENTE']].describe()

       VARIACAO PRIMEIRA HORA ANTERIOR TEMPERATURA AMBIENTE
count                                      533926.000000
mean                                            1.139043
std                                             0.972834
min                                             0.000000
25%                                             0.500000
50%                                             0.900000
75%                                             1.500000
max                                            18.200000

In [64]:
df_intermediario[['VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA AMBIENTE']].describe()

       VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA AMBIENTE
count                                      533926.000000
mean                                            1.136538
std                                             0.974221
min                                             0.000000
25%                                             0.500000
50%                                             0.900000
75%                                             1.500000
max                                            18.200000

In [65]:
df_intermediario[['VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA AMBIENTE']].describe()

       VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA AMBIENTE
count                                      533926.000000
mean                                            1.136039
std                                             0.975418
min                                             0.000000
25%                                             0.500000
50%                                             0.900000
75%                                             1.500000
max                                            18.200000

In [66]:
X = df_intermediario[['VARIACAO PRIMEIRA HORA ANTERIOR TEMPERATURA AMBIENTE']]

n_clusters = 4  

# Aplicar o K-Means
kmeans = KMeans(n_clusters = n_clusters, random_state= 10)

df_intermediario['VARIACAO PRIMEIRA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS'] = kmeans.fit_predict(X)

# Obter os centróides dos clusters 
centroids = kmeans.cluster_centers_

print("Centróides de 'VARIACAO PRIMEIRA HORA ANTERIOR TEMPERATURA AMBIENTE': ", centroids)

df_intermediario['VARIACAO PRIMEIRA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS - ROTULOS'] = df_intermediario['VARIACAO PRIMEIRA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS'].map({
    0: 'Medio',      # Cluster com centróide 1.27
    1: 'baixo',     # Cluster com 0.46
    2: 'Alto' ,     # Cluster com centróide 2.45
    3: 'Muito Alto' # 5.083
        
})

Centróides de 'VARIACAO PRIMEIRA HORA ANTERIOR TEMPERATURA AMBIENTE':  [[1.27656382]
 [0.46893433]
 [2.45077195]
 [5.08395943]]

In [67]:
centroids_manual = np.array([
    [1.27656382],
    [0.46893433],
    [2.45077195],
    [5.08395943]
])

In [68]:
X_novo = df_intermediario[['VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA AMBIENTE']]

# Calcular a distância de cada ponto aos centróides e encontrar o cluster mais próximo
df_intermediario['VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS'] = np.argmin(
    cdist(X_novo, centroids_manual), axis=1
)

# Manter os mesmos rótulos de cluster
df_intermediario['VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS - ROTULOS'] = df_intermediario[
    'VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS'
].map({
    0: 'Medio',      # Cluster com centróide 1.27
    1: 'baixo',     # Cluster com 0.46
    2: 'Alto' ,     # Cluster com centróide 2.45
    3: 'Muito Alto' # 5.083
})

df_intermediario[['VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA AMBIENTE', 
                        'VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS', 
                        'VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS - ROTULOS']]

,VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA AMBIENTE,VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS,VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS - ROTULOS
0,0.0,1,baixo
1,0.3,1,baixo
2,0.0,1,baixo
3,0.5,1,baixo
4,0.3,1,baixo
...,...,...,...
535024,1.7,0,Medio
535025,1.7,0,Medio
535026,1.5,0,Medio
535027,0.9,0,Medio
535028,0.3,1,baixo

In [69]:
X_novo = df_intermediario[['VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA AMBIENTE']]

# Calcular a distância de cada ponto aos centróides e encontrar o cluster mais próximo
df_intermediario['VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS'] = np.argmin(
    cdist(X_novo, centroids_manual), axis=1
)

# Manter os mesmos rótulos de cluster
df_intermediario['VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS - ROTULOS'] = df_intermediario[
    'VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS'
].map({
    0: 'Medio',      # Cluster com centróide 1.27
    1: 'baixo',     # Cluster com 0.46
    2: 'Alto' ,     # Cluster com centróide 2.45
    3: 'Muito Alto' # 5.083
})

df_intermediario[['VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA AMBIENTE', 
                        'VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS', 
                        'VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS - ROTULOS']]

,VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA AMBIENTE,VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS,VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS - ROTULOS
0,0.0,1,baixo
1,0.0,1,baixo
2,0.0,1,baixo
3,0.0,1,baixo
4,0.5,1,baixo
...,...,...,...
535024,1.2,0,Medio
535025,1.7,0,Medio
535026,1.7,0,Medio
535027,1.5,0,Medio
535028,0.9,0,Medio

In [85]:
caminho_parquet = r"C:\Users\Pichau\INMET\TODAS_ESTACOES\df_intermediario.parquet"

df_intermediario.to_parquet(caminho_parquet, index=False)

# Silhueta

In [44]:
X = df_intermediario[['VARIACAO PRIMEIRA HORA ANTERIOR TEMPERATURA AMBIENTE']]

silhouette_scores = []
K_range = range(2, 21)  

for k in K_range:
    kmeans = KMeans(n_clusters=k, random_state=10)
    labels = kmeans.fit_predict(X)
    sil_score = silhouette_score(X, labels)
    silhouette_scores.append(sil_score)

plt.plot(K_range, silhouette_scores, marker='o')
plt.xlabel('Número de Clusters')
plt.ylabel('Índice de Silhueta')
plt.title('Índice de Silhueta para diferentes K')
plt.show()

KeyboardInterrupt:

In [ ]:
df_intermediario['VARIACAO PRIMEIRA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS - ROTULOS'].value_counts()

In [ ]:
df_intermediario['VARIACAO SEGUNDA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS - ROTULOS'].value_counts()

In [ ]:
df_intermediario['VARIACAO TERCEIRA HORA ANTERIOR TEMPERATURA AMBIENTE CLUSTER K MEANS - ROTULOS'].value_counts()